language: android
jdk:
  - oraclejdk8
android:
  components:
    - tools # to get the new `repository-11.xml`
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra
    - tools
script:
   - ./gradlew assembleDebug