language: android
env:
  matrix:
    - ANDROID_VERSION=android-16 ANDROID_ABI=armeabi-v7a
    - ANDROID_VERSION=android-21 ANDROID_ABI=armeabi-v7a
    - ANDROID_VERSION=android-22 ANDROID_ABI=armeabi-v7a
    - ANDROID_VERSION=android-23 ANDROID_ABI=armeabi-v7a
jdk:
  - oraclejdk8
android:
  components:
    - tools
    - tools
    - build-tools-25.0.2
    - platform-tools
    - extra-android-m2repository
    - extra-google-android-support
    # The BuildTools version used by your project
    #- build-tools-19.1.0

    # The SDK version used to compile your project
    - android-16
    - android-21
    - android-22
    - android-23

    # Additional components

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-android-16
    - sys-img-armeabi-v7a-android-21
    - sys-img-armeabi-v7a-android-22
    - sys-img-armeabi-v7a-android-23
before_script:
  - echo no | android create avd --force -n test -t $ANDROID_VERSION --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
script:
   - ./gradlew connectedCheck
after_success:
   - bash <(curl -s https://codecov.io/bash)
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.android/build-cache